/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description Sonde de disponibilité : l'API ne répond qu'une fois le modèle chargé et validé.
         */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/model": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Model Info
         * @description Fiche du modèle servi : provenance MLflow, descripteurs, hyperparamètres, métriques.
         */
        get: operations["model_info_v1_model_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/predict": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Predict
         * @description Prédit la classe d'énergie de liaison d'une molécule.
         */
        post: operations["predict_v1_predict_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/predict/batch": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Predict Batch
         * @description Prédit plusieurs molécules en un appel ; les réponses suivent l'ordre de la requête.
         */
        post: operations["predict_batch_v1_predict_batch_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * BatchRequest
         * @description Lot de molécules à prédire en un seul appel.
         */
        BatchRequest: {
            /** Molecules */
            molecules: components["schemas"]["Molecule"][];
        };
        /**
         * BatchResponse
         * @description Prédictions d'un lot et version du modèle qui les a produites.
         */
        BatchResponse: {
            /**
             * Predictions
             * @description Une prédiction par molécule, dans l'ordre de la requête
             */
            predictions: components["schemas"]["Prediction"][];
            model: components["schemas"]["ModelRef"];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * Health
         * @description État de l'API et modèle servi.
         */
        Health: {
            /**
             * Status
             * @constant
             */
            status: "ok";
            model: components["schemas"]["ModelRef"];
        };
        /**
         * ModelInfo
         * @description Fiche du modèle servi.
         */
        ModelInfo: {
            /**
             * Name
             * @example sirtuin6-elastic
             */
            name: string;
            /**
             * Version
             * @example 10
             */
            version: string;
            /**
             * Alias
             * @example production
             */
            alias: string;
            /**
             * Run Id
             * @description Run MLflow qui a produit cette version
             */
            run_id: string;
            /**
             * Features
             * @description Descripteurs attendus en entrée
             */
            features: string[];
            /** Classes */
            classes: ("Low_BFE" | "High_BFE")[];
            /**
             * Positive Class
             * @enum {string}
             */
            positive_class: "Low_BFE" | "High_BFE";
            /**
             * Params
             * @description Hyperparamètres retenus par l'optimisation
             */
            params: {
                [key: string]: string;
            };
            /**
             * Metrics
             * @description Métriques loguées dans MLflow (test, CV)
             */
            metrics: {
                [key: string]: number;
            };
        };
        /**
         * ModelRef
         * @description Version du registre MLflow qui a produit la réponse (traçabilité).
         */
        ModelRef: {
            /**
             * Name
             * @example sirtuin6-elastic
             */
            name: string;
            /**
             * Version
             * @example 10
             */
            version: string;
            /**
             * Alias
             * @example production
             */
            alias: string;
        };
        /**
         * Molecule
         * @description Descripteurs moléculaires PaDEL d'une molécule, sous les noms des colonnes du dataset.
         *
         *     Valeurs finies uniquement : NaN et infini sont refusés (422) au lieu de faire échouer le modèle.
         */
        Molecule: {
            /**
             * Sc-5
             * @description Indice de connectivité de Kier-Hall : cluster simple d'ordre 5
             * @example 0.540936
             */
            "SC-5": number;
            /**
             * Sp-6
             * @description Indice de connectivité de Kier-Hall : chemin simple d'ordre 6
             * @example 7.64192
             */
            "SP-6": number;
            /**
             * Shbd
             * @description Somme des E-States des donneurs forts de liaison hydrogène
             * @example 0.162171
             */
            SHBd: number;
            /**
             * Minhaach
             * @description E-State minimal des hydrogènes portés par un CH aromatique
             * @example 0.44527
             */
            minHaaCH: number;
            /**
             * Maxwhba
             * @description E-State maximal des accepteurs faibles de liaison hydrogène
             * @example 2.20557
             */
            maxwHBa: number;
            /**
             * Fmf
             * @description Fraction des atomes lourds appartenant au squelette moléculaire (complexité)
             * @example 0.467742
             */
            FMF: number;
        };
        /**
         * Prediction
         * @description Prédiction pour une molécule.
         */
        Prediction: {
            /**
             * Label
             * @description Classe prédite : énergie de liaison élevée ou faible
             * @enum {string}
             */
            label: "Low_BFE" | "High_BFE";
            /**
             * Probabilities
             * @description Probabilité par classe (somme = 1)
             */
            probabilities: {
                [key: string]: number;
            };
        };
        /**
         * PredictionResponse
         * @description Prédiction d'une molécule et version du modèle qui l'a produite.
         */
        PredictionResponse: {
            /**
             * Label
             * @description Classe prédite : énergie de liaison élevée ou faible
             * @enum {string}
             */
            label: "Low_BFE" | "High_BFE";
            /**
             * Probabilities
             * @description Probabilité par classe (somme = 1)
             */
            probabilities: {
                [key: string]: number;
            };
            model: components["schemas"]["ModelRef"];
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
        };
    };
    model_info_v1_model_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModelInfo"];
                };
            };
        };
    };
    predict_v1_predict_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Molecule"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PredictionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    predict_batch_v1_predict_batch_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BatchRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BatchResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
